- name: running collectstatic
  shell: "{{ django_dest }}/venv/bin/python{{ django_pythonversion }} manage.py collectstatic --skip-checks -c --noinput"
  args:
    chdir: "{{ django_dest }}"
  when: django_collectstatic
  notify:
    enable django service
