---
- import_tasks: git.yml
- import_tasks: venv.yml
- import_tasks: env.yml
- import_tasks: migration.yml
- import_tasks: service.yml
- import_tasks: assets.yml
  when: django_assets
- import_tasks: collectstatic.yml
