- name: copy /etc/systemd/system/
  template:
    src: "django.service.j2"
    dest: "/etc/systemd/system/{{ django_name }}.service"
    mode: 0600
  notify:
    enable django service
    
# Conferir:
# systemctl enable macc.service
# systemctl start macc.service
# systemctl status macc.service
